.TH "QUERYPATH" "1" "2021-04-12" "" "querypath"
.SH NAME
\fBquerypath-remove\fR - remove a directory from the database
.SH SYNOPSIS
.B querypath remove [PATHS] [OPTIONS]
.SH DESCRIPTION
If you'd like to permanently exclude a directory from the database, see the
\fB_QP_EXCLUDE_DIRS\fR environment variable in \fBquerypath\fR(1).
.SH OPTIONS
.TP
.B -h, --help
Print help information.
.SH REPORTING BUGS
For any issues, feature requests, or questions, please visit:
.sp
\fBhttps://github.com/dimarogiv/querypath/issues\fR
.SH AUTHOR
Ajeet D'Souza \fB<98ajeet@gmail.com>\fR
